### ISSUE TITLE
The plugin does not work with FlowLauncher

### ISSUE THREAD

**Issue by RODDINO** [watermarkhu/FlowLauncherBitwarden#2]
the plugin does not work, I could not use the automatic installation and I manually copied the folder after that, but it kept giving me errors in entering the BitWarden token,
[2022-11-02.txt](https://github.com/watermarkhu/FlowLauncherBitwarden/files/9924325/2022-11-02.txt)
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.25231.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 11/02/2022 22:40:19
Exception:
Bitwarden Exception: 
Websites: https://github.com/watermarkhu/FlowLauncherBitwarden
Author: watermarkhu
Version: 0.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Bitwarden|Traceback (most recent call last):
  File "C:\Users\rodol\AppData\Roaming\FlowLauncher\Plugins\BitWarden\main.py", line 9, in <module>
    from plugin.main import Bitwarden
  File "C:\Users\rodol\AppData\Roaming\FlowLauncher\Plugins\BitWarden\plugin\main.py", line 5, in <module>
    import favicon, validators, webbrowser
ModuleNotFoundError: No module named 'favicon'

 ---> System.IO.InvalidDataException: Bitwarden|Traceback (most recent call last):
  File "C:\Users\rodol\AppData\Roaming\FlowLauncher\Plugins\BitWarden\main.py", line 9, in <module>
    from plugin.main import Bitwarden
  File "C:\Users\rodol\AppData\Roaming\FlowLauncher\Plugins\BitWarden\plugin\main.py", line 5, in <module>
    import favicon, validators, webbrowser
ModuleNotFoundError: No module named 'favicon'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 626
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 590
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by basavyr** [comment]
Same issue for me, almost two years later. It seems that this project is somewhat _abandoned_.

```

Please open new issue in: https://github.com/watermarkhu/FlowLauncherBitwarden/issues
1. upload log file: C:\Users\robert.poenaru\AppData\Roaming\FlowLauncher\Logs\1.17.2\2024-04-19.txt
2. copy below exception message

Flow Launcher version: 1.17.2
OS Version: 19044.4170
IntPtr Length: 8
x64: True

Python Path: C:\Users\robert.poenaru\AppData\Local\anaconda3\python.exe
Node Path: 
Date: 04/19/2024 10:25:41
Exception:
Bitwarden Exception: 
Websites: https://github.com/watermarkhu/FlowLauncherBitwarden
Author: watermarkhu
Version: 0.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\robert.poenaru\AppData\Roaming\FlowLauncher\Plugins\Bitwarden\main.py", line 9, in <module>
    from plugin.main import Bitwarden
  File "C:\Users\robert.poenaru\AppData\Roaming\FlowLauncher\Plugins\Bitwarden\plugin\main.py", line 2, in <module>
    from flox import Flox
ImportError: cannot import name 'Flox' from 'flox' (C:\Users\robert.poenaru\AppData\Local\anaconda3\Lib\site-packages\flox\__init__.py)

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\robert.poenaru\AppData\Roaming\FlowLauncher\Plugins\Bitwarden\main.py", line 9, in <module>
    from plugin.main import Bitwarden
  File "C:\Users\robert.poenaru\AppData\Roaming\FlowLauncher\Plugins\Bitwarden\plugin\main.py", line 2, in <module>
    from flox import Flox
ImportError: cannot import name 'Flox' from 'flox' (C:\Users\robert.poenaru\AppData\Local\anaconda3\Lib\site-packages\flox\__init__.py)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Edit: changed my output error, as I have provided a different Python3 version in my FlowLauncher settings (I am using python3 from Anaconda)
